title = "Erick Sauceda"
baseURL = "ericksauceda.org"
tags = ["portfolio", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
publishDir = "docs"

[Params]
    tagline = "Software Engineer"
    author = "Erick Sauceda"
    description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
    twitter = "sawsda"
    linkedin = "ericksauceda"
    github = "easauceda"
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
